version: "3.8"

x-logging: &log-env
  driver: "${LOG_DRIVER:-local}"
  options:
    max-size: "${LOG_MAX_SIZE:-128m}"
    max-file: "${LOG_MAX_FILES:-2}"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.56
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4318:4318"
    restart: unless-stopped
    logging: *log-env

  # redis:
  #   image: redis:7-alpine
  #   ports: ["6379:6379"]
  #   environment:
  #     - REDIS_RAM_SIZE=${REDIS_RAM_SIZE:-256}
  #   command: >
  #     redis-server --appendonly yes
  #                  --maxmemory ${REDIS_RAM_SIZE:-256}mb
  #                  --maxmemory-policy allkeys-lru
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
  #   logging: *log-env

volumes:
  redis_data:

# http://localhost:16686 jaeger UI
