version: '3.8'

x-logging: &log-env
  driver: "${LOG_DRIVER:-local}"
  options:
    max-size: "${LOG_MAX_SIZE:-128m}"
    max-file: "${LOG_MAX_FILES:-2}"

x-app-base: &app-base
  image: golang:${GO_VERSION:-1.25}
  working_dir: /app
  command: ["go", "run", "./cmd"]
  volumes:
    - .:/app
  restart: unless-stopped
  logging: *log-env
  env_file:
    - .env

services:
  app-direct:
    <<: *app-base
    depends_on: [redis, jaeger]
    cpus: "${APP_CPUS:-0.90}"
    mem_limit: "${APP_MEM:-512m}"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      - GOMEMLIMIT=${APP_GOMEMLIMIT:-430MiB}
      - GOGC=${GOGC:-100}

  jaeger:
    image: jaegertracing/all-in-one:1.56
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4318:4318"
    restart: unless-stopped
    logging: *log-env
    cpus: "${JAEGER_CPUS:-0.50}"
    mem_limit: "${JAEGER_MEM:-256m}"

  redis:
    image: redis:7-alpine
    volumes: [redis_data:/data]
    environment:
      - REDIS_RAM_SIZE=${REDIS_RAM_SIZE:-256}
    command: >
      redis-server --appendonly yes
                   --maxmemory ${REDIS_RAM_SIZE:-256}mb
                   --maxmemory-policy allkeys-lru
    logging: *log-env

volumes:
  redis_data:

# http://localhost:16686 jaeger UI
